# Build stage
FROM node:18-alpine as build

WORKDIR /usr/src/app

# Install python and other dependencies required for youtube-dl-exec
RUN apk add --no-cache python3 make g++ gcc

COPY ../../package*.json ./

RUN npm install

COPY ../../. .

RUN npm run build

# Production stage
FROM node:20-alpine as production

WORKDIR /usr/src/app

# Install python for youtube-dl-exec
RUN apk add --no-cache python3

# Copy package files
COPY ../../package*.json ./

# Install production dependencies only
RUN npm install --production

# Copy built files
COPY --from=build /usr/src/app/dist ./dist

EXPOSE 3000

CMD ["node", "dist/app.js"]